- name: Install Database Packages
  when: ansible_facts['hostname'] == "database"
  yum:
    name: "{{ db_packages }}"
    state: latest

#- name: Install Database2 Packages
#  when: ansible_facts['hostname'] == "database2"
#  yum:
#    name: "{{ db_packages }}"
#    state: latest    