- name: Install Application Webserver
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: "{{ app_packages }}"
    state: latest

- name: Install remi repositories
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install yum utils
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: yum-utils
    state: latest  

- name: Enable remi-php73 repository
  when: ansible_facts['hostname'] == "webserver"
  yum_repository:
    mirrorlist: http://cdn.remirepo.net/enterprise/7/php73/mirror
    description: Extra Packages for Enterprise Linux 7 - Testing - $basearch
    name: remi-php73
    enabled: yes

- name: Update Repos on Webserver
  when: ansible_facts['hostname'] == "webserver"      
  yum: 
    name: "*"
    state: latest

- name: Install php7.3
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: "{{ php_package }}"
    state: present
    enablerepo: "remi-*,base,epel"

- name: Download and unarchive WordPress
  when: ansible_facts['hostname'] == "webserver"
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy WordPress files to /var/www/html with owner and permissions
  when: ansible_facts['hostname'] == "webserver" 
  copy:
    src: /tmp/wordpress/    # we use '/' because we want to copy just content of wordpress folder
    dest: /var/www/html/
    owner: apache
    group: apache
    remote_src: yes                     